server:
  port: 8081
  

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.rupifi.lender.dfl: DEBUG

        
api:
  baseUrl: https://uat.partnerapi.idfcfirstbank.com:1448



    
